// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMachines() {
  return window['go']['main']['App']['GetMachines']();
}

export function GetRomset() {
  return window['go']['main']['App']['GetRomset']();
}

export function Play(arg1) {
  return window['go']['main']['App']['Play'](arg1);
}

export function ServeVideo(arg1, arg2) {
  return window['go']['main']['App']['ServeVideo'](arg1, arg2);
}
