// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {http} from '../models';

export function GetMachines():Promise<{[key: string]: main.machine}>;

export function GetRomset():Promise<Array<string>>;

export function Play(arg1:string):Promise<void>;

export function ServeVideo(arg1:http.ResponseWriter,arg2:http.Request):Promise<void>;
